### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Ch4r0ne** [cdp1337/ARKSurvivalAscended-Linux#1]
**Describe the bug**
Unfortunately, the script encounters multiple errors during a fresh installation of Debian 12.

user@debian12:~# su -
root@debian12:~# wget https://raw.githubusercontent.com/cdp1337/ARKSurvivalAscended-Linux/main/server-install-debian12.sh
root@debian12:~# chmod +x server-install-debian12.sh
root@debian12:~# sudo ./server-install-debian12.sh

Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
software-properties-common is already the newest version (0.99.30-4).
software-properties-common set to manually installed.
dirmngr is already the newest version (2.2.40-1.1).
dirmngr set to manually installed.
ca-certificates is already the newest version (20230311).
wget is already the newest version (1.21.3-1+b2).
sudo is already the newest version (1.9.13p3-1+deb12u1).
sudo set to manually installed.
The following NEW packages will be installed:
  apt-transport-https curl
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/340 kB of archives.
After this operation, 536 kB of additional disk space will be used.
Get:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm/main amd64 apt-transport-https all 2.6.1 [25.2 kB]
Get:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm/main amd64 curl amd64 7.88.1-10+deb12u3 [315 kB]
Selecting previously unselected package apt-transport-https.
(Reading database ... 146321 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.6.1_all.deb ...
Unpacking apt-transport-https (2.6.1) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.88.1-10+deb12u3_amd64.deb ...
Unpacking curl (7.88.1-10+deb12u3) ...
Setting up apt-transport-https (2.6.1) ...
Setting up curl (7.88.1-10+deb12u3) ...
Processing triggers for man-db (2.11.2-2) ...
Adding component(s) 'contrib non-free' to all repositories.
Enabling deb-src for all repositories.
Added contrib non-free to: deb cdrom:[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29]/ bookworm contrib non-free main non-free-firmware
Warning, missing deb-src for: deb-src cdrom:[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29]/ bookworm contrib non-free non-free-firmware main
Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Get:3 http://repo.steampowered.com/steam stable InRelease [2,861 B]
Get:4 http://repo.steampowered.com/steam stable/steam amd64 Packages [1,153 B]
Get:5 http://repo.steampowered.com/steam stable/steam i386 Packages [1,344 B]
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package lib32gcc-s1
E: Unable to locate package steamcmd
--2023-10-29 11:13:45--  https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-21/GE-Proton8-21.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
....

**Comment by Ch4r0ne** [comment]
After executing your command for the second time, unfortunately, the script still encounters errors during the installation on Debian 12.

root@debian12:~# sudo su -c "bash <(wget -qO- https://raw.githubusercontent.com/cdp1337/ARKSurvivalAscended-Linux/main/server-install-debian12.sh)" root

Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://repo.steampowered.com/steam stable InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
software-properties-common is already the newest version (0.99.30-4).
apt-transport-https is already the newest version (2.6.1).
dirmngr is already the newest version (2.2.40-1.1).
ca-certificates is already the newest version (20230311).
curl is already the newest version (7.88.1-10+deb12u3).
wget is already the newest version (1.21.3-1+b2).
sudo is already the newest version (1.9.13p3-1+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Adding component(s) 'contrib non-free' to all repositories.
Enabling deb-src for all repositories.
Added contrib non-free to: deb cdrom:[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29]/ bookworm non-free-firmware main contrib contrib non-free non-free
Warning, missing deb-src for: deb-src cdrom:[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29]/ bookworm non-free-firmware main contrib contrib non-free non-free
Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://repo.steampowered.com/steam stable InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Ign:1 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://repo.steampowered.com/steam stable InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.2.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20231007-10:29] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package lib32gcc-s1
E: Unable to locate package steamcmd
sudo: /usr/games/steamcmd: command not found
Unable to guess where Steam is installed.

**Comment by cdp1337** [comment]
ooooh, good catch!  I didn't even think about CD-only repo setups.

**Comment by cdp1337** [comment]
Potential fix for this posted.  Please re-run that bash < wget... installation line and let me know if it solves your issues.

Also this script should be safe to run multiple times.

**Comment by Ch4r0ne** [comment]
Thanks now i geht this result

.....
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package steamcmd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'steamcmd' has no installation candidate
sudo: /usr/games/steamcmd: command not found
Unable to guess where Steam is installed.
root@debian:~#

**Comment by mschnitzer** [comment]
@Ch4r0ne You need to edit `/etc/apt/sources.list` and add `non-free` to this line:

```
deb http://deb.debian.org/debian/ bookworm non-free-firmware main contrib
```

**Comment by cdp1337** [comment]
Yup, I was going to say to run `apt-add-repository -L` and let us know the output.  It _should_ contain a URL similar to what @mschnitzer posted.  I tried to fix this, but I didn't even know you could still do an install without repos enabled, so couldn't replicate your setup exactly to test it.

**Comment by Ch4r0ne** [comment]
@mschnitzer thank you very much, that could solve the problem

**Comment by Ch4r0ne** [comment]
@cdp1337 Is there a way to include this in the script in case others come across this too?

**Comment by l1zart** [comment]
maybe add something like this:

cp /etc/apt/sources.list /etc/apt/sources.list.bak
while read -r line; do
    if [[ "$line" =~ ^deb ]] && ! [[ "$line" =~ non-free ]]; then
        echo "$line non-free"
    else
        echo "$line"
    fi
done < /etc/apt/sources.list > /etc/apt/sources.list.new
mv /etc/apt/sources.list.new /etc/apt/sources.list

I implemented a backup just to be sure

**Comment by cdp1337** [comment]
Newest build should resolve this issue with the usage of `add-apt-repository -y -U http://deb.debian.org/debian -c non-free-firmware -c non-free`.
