### ISSUE TITLE
simplify code to enable repository source

### ISSUE THREAD

**Issue by Oxymoron290** [cdp1337/ARKSurvivalAscended-Linux#14]
You can replace [all the code](https://github.com/cdp1337/ARKSurvivalAscended-Linux/blob/6665e967f008975e50de64ba9e883654b6685687/server-install-debian12.sh#L30-L48) that edits the sources.list to add the necessary `non-free` and `non-free-firmware` with two simple lines:

```
apt-add-repository -s non-free
apt-add-repository -s non-free-firmware
```

the `apt-add-repository` is added as part of the `software-properties-common` installed prior to modifying the sources.list file.

Why all the unnecessary file parsing and checking if the values are already there?

**Comment by cdp1337** [comment]
Thanks for your feedback!  There was a bug in Debian 12 which made the easy solution not completely reliable.  (This is originally an Ubuntu/Canonical feature after all.)  On the newest build I was able to simplify the code a bit, though still needed to do some trickery.
