### ISSUE TITLE
Setting up a second server / cluster Island - Scorched Earth

### ISSUE THREAD

**Issue by Shanpapa** [cdp1337/ARKSurvivalAscended-Linux#18]
Hi, Can I use your install method to create a second server for scorched Earth map please? I like to run both map at the same time.
Thanks

**Comment by Shanpapa** [comment]
Just copied the main server folder into an other folder Now I have :
/home/steam/.local/share/Steam/steamapps/common/ARK Survival Ascended Scorched Earth Dedicated Server/
and
/home/steam/.local/share/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/

and changed the path in the service file, the server is running now but when restarting is not updating it :/

**Comment by Flux001337** [comment]
Hi,

here my way and it works on my server.

I Just copy my 
"/home/steam/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
to
"/home/steam/Steam/steamapps/common/ARK Scorched Earth Ascended Dedicated Server"
include all data and edit the game config.

then copy the "ark-island.service" to "ark-scorched-earth" and edit lines:

- Description=
- WorkingDirectory=
- Environment=XDG_RUNTIME_DIR=
- ExecStart

at the end run "systemctl daemon-reload" and "systemctl start ark-scorched-earth"

FINISH!!!

To check the Service run " journalctl -xeu ark-scorched-earth.service":
> 
_........
Apr 02 21:16:33 ****** steamcmd[1576524]: -- type 'quit' to exit --
Apr 02 21:16:33 ******  steamcmd[1576524]: Loading Steam API...OK
Apr 02 21:16:36 ******  steamcmd[1576524]: Connecting anonymously to Steam Public...OK
Apr 02 21:16:36 ******  steamcmd[1576524]: Waiting for client config...OK
Apr 02 21:17:01 ******  steamcmd[1576524]: Waiting for user info...OK
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 0.05 (6291456 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 6.08 (700717634 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 14.24 (1640145958 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 22.49 (2591289406 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 30.65 (3531197422 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 38.90 (4481426926 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 47.03 (5417906614 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 55.35 (6375825990 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 63.51 (7315723243 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 71.86 (8278270987 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 80.01 (9216173051 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]:  Update state (0x5) verifying install, progress: 88.18 (10157780358 / 11519475579)
Apr 02 21:17:01 ****** steamcmd[1576524]:  Update state (0x5) verifying install, progress: 96.50 (11116178822 / 11519475579)
Apr 02 21:17:01 ******  steamcmd[1576524]: Success! App '2430930' fully installed.
Apr 02 21:17:01 ******  systemd[1]: Started ark-scorched-earth.service - ARK Survival Ascended Dedicated Server 2 (Scorched Earth)._


I hope it helps ^^

**Comment by Flux001337** [comment]
**I let you know my result after the next update....**

_By the way... do not use Game port +1 for the 2. Server instance
This is the Raw UDP socket port (always Game client port +1)  

Use 777**9**   for the 2. Server instance instead._

**Comment by Shanpapa** [comment]
Thanks for reply, changed the port, run "systemctl daemon-reload" as well.

journalctl -xeu ark-scorched.service
Apr 04 08:21:30 ShanpapaGameservers steamcmd[295352]: Waiting for client config>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]: Waiting for user info...OK
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verif>
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]: Success! App '2430930' fu>
Apr 04 08:21:51 ShanpapaGameservers systemd[1]: Started ark-scorched.service - >
░░ Subject: A start job for unit ark-scorched.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit ark-scorched.service has finished successfully.
░░
░░ The job identifier is 67168.
lines 5044-5064/5064 (END)
Apr 04 08:21:30 ShanpapaGameservers steamcmd[295352]: Waiting for client config...OK
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]: Waiting for user info...OK
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 0.14 (16777216 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 10.43 (1218368607 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 20.57 (2402327379 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 30.87 (3605079531 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 41.16 (4807587151 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 51.35 (5997524979 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 61.69 (7204339240 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 71.64 (8366798408 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 81.30 (9495440936 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]:  Update state (0x5) verifying install, progress: 91.38 (10672558947 / 11679220579)
Apr 04 08:21:51 ShanpapaGameservers steamcmd[295352]: Success! App '2430930' fully installed.
Apr 04 08:21:51 ShanpapaGameservers systemd[1]: Started ark-scorched.service - ARK Survival Ascended Dedicated Server (ScorchedEarth).
░░ Subject: A start job for unit ark-scorched.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit ark-scorched.service has finished successfully.
░░
░░ The job identifier is 67168.
Regarding this, I don't see the issue, not sure why is not updated.

**Comment by Flux001337** [comment]
Try:

`ExecStartPre=/usr/games/steamcmd +force_install_dir <YoureDirectory> +login anonymous +app_update 2430930 validate +quit`

I don't know what happens if there are spaces in the path.
I think SteamCMD does not support spaces!! 
You might have to escape them.

**Comment by Shanpapa** [comment]
Hello, thank you for your response, waited for the new update but something is just messed up. server is restarting but not updated, so what I do is just sync the main folder content with the secondary folder and changing the config file at each restart, don't know what else I can do, and what coursing the issue.

rsync -av /home/steam/.local/share/Steam/steamapps/common/ARK\ Survival\ Ascended\ Dedicated\ Server/ /home/steam/.local/share/Steam/steamapps/common/ARK\ Survival\ Ascended\ Scorched\ Earth\ Dedicated\ Server/

**Comment by Shanpapa** [comment]
So I know is not the best but is working now.
I created a bash file, and is do everything

#!/bin/bash

# Running synchronization
echo "Running synchronization..."

# Restarting and updating Ark Island server
echo "Restarting and updating Ark Island server..."
systemctl restart ark-island
echo "Done."

# Waiting for the Island server to restart and update
echo "Waiting for the Ark Island server to restart and update..."
sleep 300

# Stopping Ark ScorchedEarth server
echo "Stopping Ark ScorchedEarth server..."
systemctl stop ark-scorched
echo "Done."

# Copying content from Island directory to ScorchedEarth directory
echo "Copying content from Island directory to ScorchedEarth directory..."
rsync -av /home/steam/.local/share/Steam/steamapps/common/ARK\ Survival\ Ascended\ Dedicated\ Server/ /home/steam/.local/share/Steam/steamapps/common/ARK\ Survival\ Ascended\ Scorched\ Earth\ Dedicated\ Server/
echo "Done."

# Overwriting settings
echo "Overwriting settings..."
rsync -av /home/steam/.local/share/Steam/steamapps/common/ArkScorchedSettings/WindowsServer/* /home/steam/.local/share/Steam/steamapps/common/ARK\ Survival\ Ascended\ Scorched\ Earth\ Dedicated\ Server/ShooterGame/Saved/Config/WindowsServer/
echo "Done."

# Restarting Ark ScorchedEarth server
echo "Restarting Ark ScorchedEarth server..."
systemctl start ark-scorched
echo "Done."

echo "Synchronization completed successfully."

**Comment by cdp1337** [comment]
Hey, apologies for not working on this repo in a while, but glad you found a solution.  Probably a little late now, but the newest build supports all the maps out of the box.
