### ISSUE TITLE
Check for user installed firewall before installing

### ISSUE THREAD

**Issue by APinchofDill** [cdp1337/ARKSurvivalAscended-Linux#19]
**Describe the bug**
Execution of script installed firewalld over UFW and it caused me to have to enable recovery mode to get the server back. 

**To Reproduce**
Steps to reproduce the behaviour:
1. `wget https://raw.githubusercontent.com/cdp1337/ARKSurvivalAscended-Linux/refs/heads/main/server-install-debian12.sh`
2. `chmod +x `
3. `./server-install-debian12.sh`

**Expected behaviour**
Check for user install dependencies and make sure firewall does not install if another is enabled / installed

**Screenshots**
insert blue screen of death gif

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Remote Dedicated server
 
**Additional context**
Check if `steam` user is not already on system

**Comment by cdp1337** [comment]
I apologies for the issues the script caused you; I'll look into adjusting the workflow to account for the presence of UFW and an existing Steam user.

**Comment by APinchofDill** [comment]
> I apologies for the issues the script caused you; I'll look into adjusting the workflow to account for the presence of UFW and an existing Steam user.

No worries, the script itself it a lot of help. So thank you. I should have seen the firewalld install and removed that. It crashed the server then on boot blocked ssh ports I use to connect once it was enabled.

**Comment by cdp1337** [comment]
This should be resolved now; I added a check to see if UFW is present, and if so it'll use that config instead.
