### ISSUE TITLE
Change game ports

### ISSUE THREAD

**Issue by jsbrain** [cdp1337/ARKSurvivalAscended-Linux#2]
After starting the server, I can see in netstat that the ports `7777` and `8888` are bound to `wineserver`.

Connecting through this ports from the game doesn't work though. Am I missing something?

**Comment by cdp1337** [comment]
Port 8888 is probably bound to localhost so it's not accessible; I'm not sure what it does.

UDP/7777 should work though, but unfortunately I haven't figured out how to change it to something else.  As long as netstat gives you `udp    32256      0 0.0.0.0:7777            0.0.0.0:*                           18809/wineserver` (or something similar), the game should be listening.

**Comment by jsbrain** [comment]
Yeah I noticed it just needs some time to show up in the server list but works perfectly fine with the current settings. Thanks!
